### ISSUE TITLE
Logout is not allowed using get request must be fixed using post method and csrf token

### ISSUE THREAD

**Issue by sudomanoj** [aksharahegde/django-jet-3-calm#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudomanoj** [comment]
Logout is not allowed using get request must be fixed using post method and csrf token

**Comment by aksharahegde** [comment]
thank you @sudomanoj for noticing the issue and raising the ticket. it has been fixed in PR #20
